var source_Eng = "Tono Hifumi pointed the tip of his sword at a young girl’s throat. Her slender neck trembling in fear, the girl made no sounds while staring tearfully at the katana aimed at her throat.\nThe Japanese sword is a beautiful weapon. A blade crest which is said to be “Scent of determination” is not a simple curved surface and has a personality that carries a sharpness that sublimates the real nature of the blade.";
var source_Jap = "遠野ひふみは、若い女の子の喉に剣の先端を指摘しました。彼女の喉を目的とした刀で涙ながらに見つめながら、恐怖に震え彼女の細い首は、女の子には音を作りません。\n日本刀は美しい武器です。 「判断の香り」であると言われている刃紋は、単純な曲面ではなく、ブレードの実際の性質を昇華シャープネスを運ぶ性格をしています。";
var source_Rus = "Тоно Хифуми прижал острый кончик своего меча к горлу молодой девушки. Ее тонкая шея трепетала от страха, она, не произнося ни звука, уставилась своими заплаканными глазами на оружие.\nЭто был превосходный японский меч. Его кромка лезвия, или, как говорят, «след решимости», не просто острейшая изогнутая часть, она то, что дает каждому мечу свою индивидуальность, то, в чем выражается вся его суть.";
source_Eng += "Tono Hifumi pointed the tip of his sword at a young girl’s throat. Her slender neck trembling in fear, the girl made no sounds while staring tearfully at the katana aimed at her throat.\nThe Japanese sword is a beautiful weapon. A blade crest which is said to be “Scent of determination” is not a simple curved surface and has a personality that carries a sharpness that sublimates the real nature of the blade.";
source_Jap += "遠野ひふみは、若い女の子の喉に剣の先端を指摘しました。彼女の喉を目的とした刀で涙ながらに見つめながら、恐怖に震え彼女の細い首は、女の子には音を作りません。\n日本刀は美しい武器です。 「判断の香り」であると言われている刃紋は、単純な曲面ではなく、ブレードの実際の性質を昇華シャープネスを運ぶ性格をしています。";
source_Rus += "Тоно Хифуми прижал острый кончик своего меча к горлу молодой девушки. Ее тонкая шея трепетала от страха, она, не произнося ни звука, уставилась своими заплаканными глазами на оружие.\nЭто был превосходный японский меч. Его кромка лезвия, или, как говорят, «след решимости», не просто острейшая изогнутая часть, она то, что дает каждому мечу свою индивидуальность, то, в чем выражается вся его суть.";
source_Eng += "Tono Hifumi pointed the tip of his sword at a young girl’s throat. Her slender neck trembling in fear, the girl made no sounds while staring tearfully at the katana aimed at her throat.\nThe Japanese sword is a beautiful weapon. A blade crest which is said to be “Scent of determination” is not a simple curved surface and has a personality that carries a sharpness that sublimates the real nature of the blade.";
source_Jap += "遠野ひふみは、若い女の子の喉に剣の先端を指摘しました。彼女の喉を目的とした刀で涙ながらに見つめながら、恐怖に震え彼女の細い首は、女の子には音を作りません。\n日本刀は美しい武器です。 「判断の香り」であると言われている刃紋は、単純な曲面ではなく、ブレードの実際の性質を昇華シャープネスを運ぶ性格をしています。";
source_Rus += "Тоно Хифуми прижал острый кончик своего меча к горлу молодой девушки. Ее тонкая шея трепетала от страха, она, не произнося ни звука, уставилась своими заплаканными глазами на оружие.\nЭто был превосходный японский меч. Его кромка лезвия, или, как говорят, «след решимости», не просто острейшая изогнутая часть, она то, что дает каждому мечу свою индивидуальность, то, в чем выражается вся его суть.";
source_Eng += "Tono Hifumi pointed the tip of his sword at a young girl’s throat. Her slender neck trembling in fear, the girl made no sounds while staring tearfully at the katana aimed at her throat.\nThe Japanese sword is a beautiful weapon. A blade crest which is said to be “Scent of determination” is not a simple curved surface and has a personality that carries a sharpness that sublimates the real nature of the blade.";
source_Jap += "遠野ひふみは、若い女の子の喉に剣の先端を指摘しました。彼女の喉を目的とした刀で涙ながらに見つめながら、恐怖に震え彼女の細い首は、女の子には音を作りません。\n日本刀は美しい武器です。 「判断の香り」であると言われている刃紋は、単純な曲面ではなく、ブレードの実際の性質を昇華シャープネスを運ぶ性格をしています。";
source_Rus += "Тоно Хифуми прижал острый кончик своего меча к горлу молодой девушки. Ее тонкая шея трепетала от страха, она, не произнося ни звука, уставилась своими заплаканными глазами на оружие.\nЭто был превосходный японский меч. Его кромка лезвия, или, как говорят, «след решимости», не просто острейшая изогнутая часть, она то, что дает каждому мечу свою индивидуальность, то, в чем выражается вся его суть.";
source_Eng += "Tono Hifumi pointed the tip of his sword at a young girl’s throat. Her slender neck trembling in fear, the girl made no sounds while staring tearfully at the katana aimed at her throat.\nThe Japanese sword is a beautiful weapon. A blade crest which is said to be “Scent of determination” is not a simple curved surface and has a personality that carries a sharpness that sublimates the real nature of the blade.";
source_Jap += "遠野ひふみは、若い女の子の喉に剣の先端を指摘しました。彼女の喉を目的とした刀で涙ながらに見つめながら、恐怖に震え彼女の細い首は、女の子には音を作りません。\n日本刀は美しい武器です。 「判断の香り」であると言われている刃紋は、単純な曲面ではなく、ブレードの実際の性質を昇華シャープネスを運ぶ性格をしています。";
source_Rus += "Тоно Хифуми прижал острый кончик своего меча к горлу молодой девушки. Ее тонкая шея трепетала от страха, она, не произнося ни звука, уставилась своими заплаканными глазами на оружие.\nЭто был превосходный японский меч. Его кромка лезвия, или, как говорят, «след решимости», не просто острейшая изогнутая часть, она то, что дает каждому мечу свою индивидуальность, то, в чем выражается вся его суть.";
source_Eng += "Tono Hifumi pointed the tip of his sword at a young girl’s throat. Her slender neck trembling in fear, the girl made no sounds while staring tearfully at the katana aimed at her throat.\nThe Japanese sword is a beautiful weapon. A blade crest which is said to be “Scent of determination” is not a simple curved surface and has a personality that carries a sharpness that sublimates the real nature of the blade.";
source_Jap += "遠野ひふみは、若い女の子の喉に剣の先端を指摘しました。彼女の喉を目的とした刀で涙ながらに見つめながら、恐怖に震え彼女の細い首は、女の子には音を作りません。\n日本刀は美しい武器です。 「判断の香り」であると言われている刃紋は、単純な曲面ではなく、ブレードの実際の性質を昇華シャープネスを運ぶ性格をしています。";
source_Rus += "Тоно Хифуми прижал острый кончик своего меча к горлу молодой девушки. Ее тонкая шея трепетала от страха, она, не произнося ни звука, уставилась своими заплаканными глазами на оружие.\nЭто был превосходный японский меч. Его кромка лезвия, или, как говорят, «след решимости», не просто острейшая изогнутая часть, она то, что дает каждому мечу свою индивидуальность, то, в чем выражается вся его суть.";
source_Eng += "Tono Hifumi pointed the tip of his sword at a young girl’s throat. Her slender neck trembling in fear, the girl made no sounds while staring tearfully at the katana aimed at her throat.\nThe Japanese sword is a beautiful weapon. A blade crest which is said to be “Scent of determination” is not a simple curved surface and has a personality that carries a sharpness that sublimates the real nature of the blade.";
source_Jap += "遠野ひふみは、若い女の子の喉に剣の先端を指摘しました。彼女の喉を目的とした刀で涙ながらに見つめながら、恐怖に震え彼女の細い首は、女の子には音を作りません。\n日本刀は美しい武器です。 「判断の香り」であると言われている刃紋は、単純な曲面ではなく、ブレードの実際の性質を昇華シャープネスを運ぶ性格をしています。";
source_Rus += "Тоно Хифуми прижал острый кончик своего меча к горлу молодой девушки. Ее тонкая шея трепетала от страха, она, не произнося ни звука, уставилась своими заплаканными глазами на оружие.\nЭто был превосходный японский меч. Его кромка лезвия, или, как говорят, «след решимости», не просто острейшая изогнутая часть, она то, что дает каждому мечу свою индивидуальность, то, в чем выражается вся его суть.";


var source_editor3 = 'asdadsadsads';